# General
permalink   : /:categories/:title/
highlighter : rouge
# Build settings
markdown: kramdown
theme: minima

title: UST
email: office@ustaviation.com
description: "ust, aviation, taxi tech, mayank tripathi, far 145 certified, aircraft, aircraft maintenance, staffing to airlines"
#baseurl: https://ustaviation.com
#url: https://ustaviation.com
repositoty: https://github.com/sierramoore/ust


sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/"]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 10 versions

