title: UST
email: office@ustaviation.com
description: ""
baseurl: "/ust"
url: http://ustaviation.com
repositoty: https://github.com/sierramoore/ust


sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/"]

# Build settings
markdown: kramdown
theme: minima


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 10 versions

