title: UST
email: sierra.v.moore@gmail.com
description: ""
baseurl: "/ust"
url: "https://sierramoore.github.io/ust"
github_username:  sierramoore

sass:
  sass_dir: _sass
  style: compressed

exclude: [".idea/"]

# Build settings
markdown: kramdown
theme: minima


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 10 versions

